[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pylegifrance"
version = "0.0.3"
description = "Librairie qui fournit des fonctions simples pour rechercher dans legifrance"
dependencies = [
    "pydantic>=2",
    "requests",
    "PyYAML",
]
requires-python = ">=3.8"
readme = "readme.md"
authors = [{name = "RaphaÃ«l d'Assignies", email = "rdassignies@protonmail.ch"}]
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/rdassignies/pylegifrance"

[project.optional-dependencies]
dev = ["pytest>=7.0", "twine>=4.0.2"]

[tool.setuptools]
package-data = {"pylegifrance" = ["pylegifrance/config.yaml"]}

